### PR TITLE
Fix #11

### LINKED ISSUE #11: May get a wrong result while calculating decimal data to hexdecimal data.
For instance:
While typing 3840x2160, well, these are decimal datas. But when you convert 3840 to hexdecimal data, it should be 0x1e00. 
But your code...
`gRes_VAL=$(echo "00000$gHeight 00000$gWide 00000001 00200000")`
So, 000001e00 is obviously wrong. So now I understand why your script cannot enable HiDPI. That is, when typing 1920x1080, the 2x resoultion, 3840x2160's data is wrong!!!

### PR DESCRIPTION
**Pull request by Artoria2e5**

### CODE REVIEW

**Comment by syscl** [comment]
@Artoria2e5 Thx Artoria, I'm really appreciate! Since I am so busy these days, I have to sit down to see/test your code and then carefully merge it. 

Again, thanks for your contribution for this project to make it better than ever, and don't hesitate to pull merge/optimise for it ;)

Best wishes,
syscl

**Comment by syscl** [comment]
@Artoria2e5 

At a glance of the code, 

```sh
gRes_VAL=$(printf '%08x ' "$gheight" "$gwide" $((0x1)) $((0x200000)))
```
should be 
```sh
gRes_VAL=$(printf '%08x ' "$gHeight" "$gWide" $((0x1)) $((0x200000)))
```

With the following 
```sh
${gRes_Val% }
```
should be
```sh
${gRes_VAL% }
```
But I do not know what's the meaning of ```${gRes_VAL% }```

syscl

**Comment by Artoria2e5** [comment]
`${gRes_VAL% }` means 'the result of stripping the suffix ` ` from `$gRes_VAL`'. In this case I am cleaning up the result of me being lazy with that `printf`. (I should have written `gRes_VAL=$(printf '%08x %08x 00000001 02000000' $gWidth $gHeight`, but was toooo lazy).

**Comment by syscl** [comment]
@Artoria2e5 
So, as you said, if I use this 
```sh
gRes_VAL=$(printf '%08x %08x 00000001 02000000' $gWidth $gHeight)
```
then I do no more need the following
```sh
gRes_VAL=${gRes_VAL% }
```
Right?

Thanks,
syscl

**Comment by Artoria2e5** [comment]
Yes.

**Pull request merged**
